name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
      BACKEND_DIR: backend
      FRONTEND_DIR: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ─── BACKEND ──────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ─── FRONTEND ─────────────────────────────────────────────
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build React app
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          npm install
          npm run build

      # ─── DEPLOY TO EC2 ────────────────────────────────────────
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./"
          target: "/home/${{ secrets.EC2_USER }}/resume-parser-app"

      - name: SSH to EC2 and restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/resume-parser-app/backend
            pip3 install -r requirements.txt
            pkill uvicorn || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
